# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#
# This configuration file is placed in '/etc/modules-load.d/'
# to force kernel to load audio drivers explicitly during
# early boot.
#
# By defining modules in a layered dependency order, it
# prevents delays caused by resolving module dependencies
# dynamically during udev hardware detection.

qrtr-smd
rpmsg_ctrl
qcom_q6v5_pas
fastrpc
snd-soc-dmic
snd-soc-max98357a
snd-soc-hdmi-codec
q6apm-dai
q6apm-lpass-dais
snd-soc-sc8280xp
audioreach_driver
